"""Django settings for BFD9000 project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from __future__ import annotations

import enum
import logging
import os
import sys
import tempfile
from pathlib import Path
from types import MappingProxyType
from typing import TYPE_CHECKING, final, override

import dotenv
from archive.storage.box import BoxStorageBackend
from archive.storage.boxtypes import BoxAuthTypes
from archive.storage.django import DjangoStorageAdapter
from archive.storage.local import LocalStorageBackend
from archive.storage.urihandler import URIStorageBackend
from django_stubs_ext import monkeypatch

monkeypatch()
if TYPE_CHECKING:
    from collections.abc import Mapping

AUTH_USER_MODEL = "auth.User"


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
denv = dotenv.dotenv_values()


def _read_secret(name: str, default: str | None = None) -> str:
    """Return the value of secret *name*, or *default* if not found.

    Resolution order:
    1. Environment variable ``name``
    2. Dotenv resolution from ``.env`` file
    2. Docker Compose secret file ``/run/secrets/<name>``
    3. *default*

    Returns:
        The secret, if found, else empty string

    """
    value = os.environ.get(name) or denv.get(name)
    if value is not None:
        return value
    secret_path = Path(f"/run/secrets/{name}")
    if secret_path.is_file():
        return secret_path.read_text(encoding="utf-8").strip() or ""
    return default or ""


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _read_secret("DEBUG", "True") == "True"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _read_secret(
    "SECRET_KEY", "django-insecure-+6m#s88j*)qb+a%2s%cw31e2k04um&*a-fk!jgcpl3849(w4sm"
)

# Box.com Configuration
BOX_DEVELOPER_TOKEN = _read_secret("BOX_DEVELOPER_TOKEN")
BOX_JWT_CONFIG_FILE = _read_secret("BOX_JWT_CONFIG_FILE")
BOX_FOLDER_ID = _read_secret("BOX_FOLDER_ID")
# Disable OAuth for now
# BOX_OAUTH_CLIENT_ID = _read_secret("BOX_OAUTH_CLIENT_ID")
# BOX_OAUTH_CLIENT_SECRET = _read_secret("BOX_OAUTH_CLIENT_SECRET")
# # Optional: explicit redirect URI for Box OAuth callback
# # (defaults to auto-detected from request)
# BOX_OAUTH_REDIRECT_URI = _read_secret("BOX_OAUTH_REDIRECT_URI")
# # Path prefix for the shelve file used to persist Box OAuth tokens
# BOX_TOKEN_STORAGE_PATH = Path(
#     _read_secret("BOX_TOKEN_STORAGE_PATH") or BASE_DIR / ".box_token"
# )

BOX_AUTH = (
    BoxAuthTypes.BoxDevToken(BOX_DEVELOPER_TOKEN)
    if BOX_DEVELOPER_TOKEN
    else BoxAuthTypes.BoxJWT(Path(BOX_JWT_CONFIG_FILE or "box_config.json"))
)


class StorageURIs(enum.StrEnum):
    """Available Storage URIs"""

    BOX = "box"
    LOCAL = "local"


MAX_IMAGE_SIZE = 100 * 1024 * 1024
MAX_9020_SIZE = 50 * 1024 * 1024
file_storage: URIStorageBackend[int]

if DEBUG:
    if _read_secret("DEBUG_USE_BOX", "False") != "False":
        file_storage = URIStorageBackend(
            {StorageURIs.BOX: BoxStorageBackend(BOX_AUTH, BOX_FOLDER_ID)}
        )
    else:
        temp_dir: tempfile.TemporaryDirectory[str] = tempfile.TemporaryDirectory()
        base_path = Path(temp_dir.name).resolve()
        file_storage = URIStorageBackend(
            {StorageURIs.BOX: LocalStorageBackend(base_path)}
        )
else:
    file_storage = URIStorageBackend(
        {StorageURIs.BOX: BoxStorageBackend(BOX_AUTH, BOX_FOLDER_ID)}
    )


def GET_DJANGO_STORAGE() -> DjangoStorageAdapter[int]:  # noqa: N802
    """Get the default Django storage module for this project

    Returns:
        A Django Storage Adapter object

    """
    return DjangoStorageAdapter(file_storage)


APP_VERSION_FILE = BASE_DIR / "VERSION"
APP_VERSION = (
    _read_secret("APP_VERSION")
    or APP_VERSION_FILE.read_text(encoding="utf-8").strip()
    or "nover"
)

if not DEBUG and "SECRET_KEY" not in os.environ:
    raise RuntimeError("SECRET_KEY must be set when DEBUG=False")

ALLOWED_HOSTS = _read_secret("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "rest_framework",
    "corsheaders",
    "django_filters",
    "drf_spectacular",
    "django_cas_ng",
    # Local apps
    "archive",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # CORS Middleware must be before CommonMiddleware
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_cas_ng.middleware.CASMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "BFD9000.urls"

TEMPLATES = [  # pyright: ignore[reportUnknownVariableType]
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "BFD9000.context_processors.app_version",
                "BFD9000.context_processors.script_name_prefix",
            ],
        },
    },
]

WSGI_APPLICATION = "BFD9000.wsgi.application"


# Database
# Use DB_ENGINE env var to select backend:
#   unset / "django.db.backends.sqlite3"    SQLite (local runserver, default)
#   "django.db.backends.postgresql"         PostgreSQL (docker-compose / production)
_db_engine = _read_secret("DB_ENGINE", "django.db.backends.sqlite3")
DATABASES = (
    {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db" / "db.sqlite3",
        }
    }
    if _db_engine == "django.db.backends.sqlite3"
    else {
        "default": {
            "ENGINE": _db_engine,
            "NAME": _read_secret("DB_NAME", "bfd9000"),
            "USER": _read_secret("DB_USER", "bfd9000"),
            "PASSWORD": _read_secret("DB_PASSWORD", ""),
            "HOST": _read_secret("DB_HOST", "db"),
            "PORT": _read_secret("DB_PORT", "5432"),
        }
    }
)

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation."
        + "UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Subpath hosting config (DJANGO_FORCE_SCRIPT_NAME env)
FORCE_SCRIPT_NAME = _read_secret("DJANGO_FORCE_SCRIPT_NAME", None) or None


# Prefix-aware STATIC_URL and MEDIA_URL
def _prefix_url(path: str) -> str:
    if FORCE_SCRIPT_NAME:
        return f"{FORCE_SCRIPT_NAME.rstrip('/')}/{path.lstrip('/')}"
    return f"/{path.lstrip('/')}"


STATIC_URL = _prefix_url("static/")
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files (Uploads)
MEDIA_URL = _prefix_url("media/")
MEDIA_ROOT = Path(_read_secret("DJANGO_MEDIA_ROOT") or BASE_DIR / "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework Configuration
REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissions",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "EXCEPTION_HANDLER": "BFD9000.exceptions.custom_exception_handler",
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ]
    if not DEBUG
    else [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "BFD9000 API",
    "DESCRIPTION": "API for BFD9000 Medical Imaging System",
    "VERSION": APP_VERSION,
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SERVE_PERMISSIONS": ["rest_framework.permissions.IsAuthenticated"],
}

# Authentication
LOGIN_REDIRECT_URL = "archive:index"  # Named route, prefix-safe
LOGIN_URL = "login"

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "django_cas_ng.backends.CASBackend",
)

CAS_SERVER_URL = os.environ.get("CAS_ENDPOINT", "https://login.case.edu/cas/")
CAS_VERSION = "3"
CAS_ROOT_PROXIED_AS = os.environ.get("PROXIED_URL", "https://localhost:4430")
CAS_REDIRECT_URL = LOGIN_REDIRECT_URL
CAS_CREATE_USER = True
CAS_CREATE_USER_WITH_LOG_IN = True
CAS_IGNORE_REFERER = True

# Proxy settings for caddy

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# CORS Configuration
CORS_ALLOWED_ORIGINS = _read_secret(
    "CORS_ALLOWED_ORIGINS", "http://localhost:5173,http://127.0.0.1:5173"
).split(",")

# CSRF trusted origins — required when Django is accessed from a different
# origin or behind a reverse proxy. This is separate from CORS_ALLOWED_ORIGINS:
# CORS_ALLOWED_ORIGINS controls cross-origin response headers (django-cors-headers),
# while CSRF_TRUSTED_ORIGINS is checked by Django's own CsrfViewMiddleware on
# every unsafe request (POST, PUT, PATCH, DELETE).
# Must include scheme, e.g.: https://example.com
_csrf_trusted = _read_secret("CSRF_TRUSTED_ORIGINS", "").strip()
CSRF_TRUSTED_ORIGINS: list[str] = [
    o.strip() for o in _csrf_trusted.split(",") if o.strip()
]

SCANNER_API_BASE = _read_secret("SCANNER_API_BASE", "http://localhost:5000")
SCANNER_DEVICE_ID = _read_secret("SCANNER_DEVICE_ID", "scanner-001")
BFD9020_BASE_URL = _read_secret("BFD9020_BASE_URL", "http://bfd9020:9020")


# Logging Configuration
@final
class PrettyFormatter(logging.Formatter):
    """A custom formatter to add color to stdout log records."""

    GRAY = "\x1b[90m"
    YELLOW = "\x1b[33;21m"
    RED = "\x1b[31;21m"
    BOLD_RED = "\x1b[31;1m"
    RESET = "\x1b[0m"

    # Define a different format for each level
    FORMATS: Mapping[int, str] = MappingProxyType(
        {
            logging.DEBUG: f"{GRAY}%(asctime)s {GRAY}DEBUG {GRAY}%(name)s: {
                RESET
            }%(message)s",
            logging.INFO: f"{GRAY}%(asctime)s {RESET}INFO  {GRAY}%(name)s: {
                RESET
            }%(message)s",
            logging.WARNING: f"{GRAY}%(asctime)s {YELLOW}WARN  {GRAY}%(name)s: {
                RESET
            }%(message)s",
            logging.ERROR: f"{GRAY}%(asctime)s {RED}ERROR {GRAY}%(name)s: {
                RESET
            }%(message)s",
            logging.CRITICAL: f"{GRAY}%(asctime)s {BOLD_RED}CRIT  {GRAY}%(name)s: {
                RESET
            }%(message)s",
        }
    )

    @override
    def format(self, record: logging.LogRecord) -> str:
        use_color = hasattr(sys.stderr, "isatty") and sys.stderr.isatty()
        log_fmt = (
            self.FORMATS.get(record.levelno)
            if use_color
            else "%(asctime)s %(levelname)-5s %(name)s: %(message)s"
        )
        return logging.Formatter(log_fmt).format(record)


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "pretty": {
            "()": PrettyFormatter,
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "pretty",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "archive": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Thumbnail generation policy (staging and UI previews)
THUMBNAIL_MAX_WIDTH = int(_read_secret("THUMBNAIL_MAX_WIDTH", "300"))
THUMBNAIL_MAX_HEIGHT = int(_read_secret("THUMBNAIL_MAX_HEIGHT", "300"))
THUMBNAIL_TARGET_BYTES = int(_read_secret("THUMBNAIL_TARGET_BYTES", str(20 * 1024)))
THUMBNAIL_HARD_MAX_BYTES = int(
    _read_secret("THUMBNAIL_HARD_MAX_BYTES", str(100 * 1024))
)
THUMBNAIL_DEFAULT_QUALITY = int(_read_secret("THUMBNAIL_DEFAULT_QUALITY", "75"))
THUMBNAIL_MIN_QUALITY = int(_read_secret("THUMBNAIL_MIN_QUALITY", "40"))
