# Generated by Django 6.0.6 on 2026-06-03 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_seed_codings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('country', 'city'), 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='archivelocation',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='coding',
            options={'ordering': ('system', 'code')},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('short_name',)},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('display_name',)},
        ),
        migrations.AlterModelOptions(
            name='digitalrecord',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ('-actual_period_start',)},
        ),
        migrations.AlterModelOptions(
            name='endpoint',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='identifier',
            options={'ordering': ('system', 'value')},
        ),
        migrations.AlterModelOptions(
            name='imagingstudy',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Imaging Studies'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='physicallocation',
            options={'ordering': ('cabinet', 'shelf', 'slot')},
        ),
        migrations.AlterModelOptions(
            name='physicalrecord',
            options={'ordering': ('-acquisition_datetime',)},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ('imaging_study',), 'verbose_name_plural': 'Series'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ()},
        ),
        migrations.AlterModelOptions(
            name='valueset',
            options={'ordering': ('slug',)},
        ),
        migrations.AlterModelOptions(
            name='valuesetconcept',
            options={'ordering': ()},
        ),
    ]
