name: Run All Tests

on:
  # Only run when a review is requested on a PR (not on push, open, etc)
  pull_request:
    types: [review_requested]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Run All tests
        run: |
          nix flake check --keep-going
